services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=strongPassword!!
    ports:
      - 1433:1433

  api:
    image: api-demo
    build:
      context: .
      dockerfile: .\APIDemo.API\Dockerfile
    environment:
      - DatabaseConnection=Data Source=db,1433;Initial Catalog=APIDemo;User ID=SA;Password=strongPassword!!;Encrypt=False
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Information
    depends_on:
      - db
    ports:
      - 8080:8080
